# Generated by Django 5.1.2 on 2024-10-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_gestion_qr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serial',
            name='url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
