# Generated by Django 5.1.2 on 2024-10-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_gestion_qr', '0002_serial_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
