# Generated by Django 5.1.2 on 2024-10-31 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_gestion_qr', '0003_categoria_slug_cliente_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serial',
            name='categoria',
        ),
        migrations.AddField(
            model_name='serial',
            name='estado',
            field=models.CharField(choices=[('programado', 'Programado'), ('en_proceso', 'En Proceso'), ('despachado', 'Despachado - listo para distribución'), ('distribucion', 'Distribución'), ('cancelado', 'Cancelado')], default='programado', max_length=20),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
