# Generated by Django 5.1.2 on 2024-10-31 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_gestion_qr', '0005_cliente_codigo_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='codigo_cliente',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
