# Generated by Django 5.1.2 on 2024-10-31 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_gestion_qr', '0006_alter_cliente_codigo_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_gestion_qr.cliente'),
        ),
        migrations.AddField(
            model_name='producto',
            name='codigo_producto',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
