# Generated by Django 5.1.2 on 2024-10-31 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_gestion_qr', '0008_template_clientetemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampoDinamico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('valor', models.CharField(max_length=200)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos_dinamicos', to='modulo_gestion_qr.producto')),
            ],
        ),
    ]
