# Generated by Django 5.1.2 on 2024-10-31 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_gestion_qr', '0009_campodinamico'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CampoDinamico',
            new_name='CampoAdicional',
        ),
    ]
