# Generated by Django 5.1.3 on 2024-11-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_gestion_qr', '0010_rename_campodinamico_campoadicional'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion_producto',
            field=models.TextField(default='prueb'),
            preserve_default=False,
        ),
    ]
