# Generated by Django 5.1.3 on 2024-12-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_gestion_qr', '0011_producto_descripcion_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='serial',
            name='campo1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='serial',
            name='campo2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='serial',
            name='campo3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='serial',
            name='campo4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='serial',
            name='campo5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
