# Generated by Django 5.1.3 on 2024-12-17 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_gestion_qr', '0012_serial_campo1_serial_campo2_serial_campo3_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CampoAdicional',
        ),
    ]
