# Generated by Django 5.1.3 on 2024-12-17 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_gestion_qr', '0013_delete_campoadicional'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_gestion_qr.cliente')),
            ],
        ),
        migrations.DeleteModel(
            name='ClienteTemplate',
        ),
    ]
