# Generated by Django 5.1.3 on 2025-01-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_gestion_qr', '0015_rol_alter_templatecliente_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='nombre_campo1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='nombre_campo2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='nombre_campo3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='nombre_campo4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='nombre_campo5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
