# Generated by Django 5.1.3 on 2025-01-29 18:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_gestion_qr', '0016_producto_nombre_campo1_producto_nombre_campo2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Template',
        ),
        migrations.AlterModelOptions(
            name='templatecliente',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.AddField(
            model_name='templatecliente',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si este template está en uso'),
        ),
        migrations.AlterField(
            model_name='templatecliente',
            name='nombre',
            field=models.CharField(help_text='Ejemplo: cliente_1.html', max_length=100, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_nombre', message='El nombre solo puede contener letras, números, guiones bajos (_) y guiones (-).', regex='^[a-zA-Z0-9_-]+$')]),
        ),
    ]
