# Generated by Django 5.1.3 on 2025-01-29 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_gestion_qr', '0017_delete_template_alter_templatecliente_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modulo_gestion_qr.templatecliente'),
        ),
    ]
