# Generated by Django 5.1.3 on 2025-02-13 13:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_gestion_qr', '0018_producto_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatecliente',
            name='nombre',
            field=models.CharField(help_text='Ejemplo: producto_template1.html', max_length=100, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_nombre', message='El nombre solo puede contener letras, números, puntos (.), guiones bajos (_) y guiones (-).', regex='^[a-zA-Z0-9_.-]+$')]),
        ),
    ]
