# Generated by Django 5.1.3 on 2025-03-26 12:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_gestion_qr', '0019_alter_templatecliente_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='serial',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
