# Generated by Django 5.1.3 on 2025-04-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_gestion_qr', '0020_serial_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serial',
            name='campo1',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serial',
            name='campo2',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serial',
            name='campo3',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serial',
            name='campo4',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serial',
            name='campo5',
            field=models.CharField(blank=True, null=True),
        ),
    ]
