# Generated by Django 5.1.3 on 2025-06-09 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_gestion_qr', '0021_alter_serial_campo1_alter_serial_campo2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_empresas/')),
                ('sobre_nosotros', models.TextField(blank=True)),
                ('razon_social', models.CharField(max_length=255)),
                ('nit', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('pagina_web', models.URLField(blank=True)),
                ('link_adicional', models.URLField(blank=True)),
                ('cajas', models.PositiveIntegerField()),
                ('rollos', models.PositiveIntegerField()),
                ('seriales', models.PositiveIntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=100)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones', to='modulo_gestion_qr.solicitud')),
            ],
        ),
    ]
