# Generated by Django 5.1.3 on 2025-06-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_gestion_qr', '0022_solicitud_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
