# Generated by Django 5.1.3 on 2025-07-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_gestion_qr', '0023_alter_solicitud_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serial',
            name='campo1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serial',
            name='campo2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serial',
            name='campo3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serial',
            name='campo4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serial',
            name='campo5',
            field=models.TextField(blank=True, null=True),
        ),
    ]
