# Generated by Django 5.1.3 on 2025-08-06 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_gestion_qr', '0024_alter_serial_campo1_alter_serial_campo2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='celular',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='direccion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='telefono',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
