# Generated by Django 5.1.3 on 2025-08-06 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_gestion_qr', '0025_solicitud_celular_solicitud_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serial',
            name='solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seriales_qr', to='modulo_gestion_qr.solicitud'),
        ),
    ]
