# Generated by Django 5.1.3 on 2025-08-06 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_gestion_qr', '0026_serial_solicitud'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('foto', models.ImageField(upload_to='entregas/fotos/')),
                ('firma', models.ImageField(upload_to='entregas/firmas/')),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True)),
                ('serial', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entrega', to='modulo_gestion_qr.serial')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='modulo_gestion_qr.solicitud')),
            ],
        ),
    ]
