# Generated by Django 5.1.3 on 2025-10-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_gestion_qr', '0027_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='mostrar_boton_entrega',
            field=models.BooleanField(default=False, verbose_name='Mostrar botón de confirmar entrega'),
        ),
    ]
