# Generated by Django 5.1.3 on 2025-10-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_gestion_qr', '0028_solicitud_mostrar_boton_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
