# Generated by Django 5.1.3 on 2025-10-20 18:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_gestion_qr', '0029_solicitud_fecha_actualizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatecliente',
            name='nombre',
            field=models.CharField(help_text='Ejemplo: producto_template1.html', max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_nombre', message='El nombre solo puede contener letras, números, puntos (.), guiones bajos (_) y guiones (-).', regex='^[a-zA-Z0-9_.-]+$')]),
        ),
        migrations.AddConstraint(
            model_name='templatecliente',
            constraint=models.UniqueConstraint(fields=('cliente', 'nombre'), name='uniq_template_por_cliente_y_nombre'),
        ),
    ]
