# Generated by Django 5.1.3 on 2025-10-24 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_gestion_qr', '0030_alter_templatecliente_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serial',
            name='max_entregas',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='serial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='modulo_gestion_qr.serial'),
        ),
    ]
