# Generated by Django 5.1.3 on 2025-10-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_gestion_qr', '0031_serial_max_entregas_alter_entrega_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serial',
            name='max_entregas',
            field=models.PositiveIntegerField(default=544),
        ),
    ]
